### ISSUE TITLE
initialize_urls not working on Rails5

### ISSUE THREAD

**Issue by ZakharDay** [rsl/stringex#190]
Working with Rails5 and using in Rails console Post.initialize_urls I was thrown with an error: ArgumentError: unknown keyword: conditions.

Full stack trace:
```
> Post.initialize_urls

ArgumentError: unknown keyword: conditions
       	from /Users/zakharday/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/relation/batches.rb:56:in `find_each'
       	from /Users/zakharday/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/querying.rb:9:in `find_each'
       	from /Users/zakharday/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/stringex-2.1.0/lib/stringex/acts_as_url/adapter/active_record.rb:14:in `klass_previous_instances'
       	from /Users/zakharday/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/stringex-2.1.0/lib/stringex/acts_as_url/adapter/base.rb:30:in `initialize_urls!'
       	from /Users/zakharday/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/stringex-2.1.0/lib/stringex/acts_as_url.rb:90:in `initialize_urls'
       	from (irb):4
       	from /Users/zakharday/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
       	from /Users/zakharday/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
       	from /Users/zakharday/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
       	from /Users/zakharday/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
       	from /Users/zakharday/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
       	from bin/rails:4:in `require'
       	from bin/rails:4:in `<main>'
```

**Comment by ZakharDay** [comment]
I've made fast patch copying previous ActiveRecord implementation of find_each. May be it's not the best fix, but it works for me right now.

**Comment by ZakharDay** [comment]
https://github.com/rsl/stringex/pull/191
